### PR TITLE
things that are done with brics

### PR DESCRIPTION
**Pull request by zml2008**
we should probably discuss asset licensing -- i've used sounds from my collection to build some of the effects which are not 100% freely redistributable, and we may want to replace those.

### CODE REVIEW

**Comment by halotroop2288** [comment]
I think any sound which is not LGPL-compatible should not be used. Sorry.

**Comment by zml2008** [comment]
LGPL is not a media license -- we'd want to decide on something like creative commons

**Comment by kvverti** [comment]
Please remove the `assets-work` directory and/or put it int the gitignore.

**Comment by zml2008** [comment]
The goal with including the assets-work folder is to provide original project files for anyone wishing to alter the sound effects. It doesn't make much difference for any of the content we have at the moment, since it's fairly simple, but if anything larger comes in, having the original project files makes the assets a lot more maintainable.

**Pull request closed without merging**
